#!/usr/bin/env bash
set -o errexit

main() {
  local tmp
  tmp="$(mktemp -d)"

  curl -sSL 'https://github.com/keithf4/pg_partman/archive/v2.6.4.tar.gz' \
    | tar -xzf - -C "${tmp}"

  make install -C "${tmp}/pg_partman-2.6.4"
}

main "$@"
